version: '3'

services:
  migagajs-development:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: migagajs-development
    working_dir: /app
    command: "tail -f /dev/null"
    volumes:
      - ./:/app